# Generated by Django 5.0.6 on 2024-08-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yinyang', '0004_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('WORK', 'Work'), ('PERSONAL', 'Personal'), ('RELATIONSHIP', 'Relationship'), ('STUDIES', 'Studies'), ('MONEY', 'Money'), ('FAMILY', 'Family'), ('HEALTH', 'Health')], default='PERSONAL', max_length=50),
        ),
    ]
