# Generated by Django 5.0.6 on 2024-08-28 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yinyang', '0005_goal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reward_type', models.CharField(choices=[('BADGE', 'Badge')], default=None, max_length=50)),
                ('receiver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reward_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
