# Generated by Django 5.0.6 on 2024-08-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yinyang', '0006_user_badges_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewards',
            name='description',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
