# Generated by Django 5.0.6 on 2024-09-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yinyang', '0007_rewards_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='media/fallback.png', upload_to='media'),
        ),
    ]
