# Generated by Django 5.0.6 on 2024-10-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yinyang', '0008_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='media'),
        ),
    ]
